# Generated by Django 4.2.4 on 2023-11-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('pasajeros', models.IntegerField()),
                ('orientacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAlojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPasajero', models.IntegerField()),
                ('idHabitacion', models.IntegerField()),
                ('idServicio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idResponsable', models.IntegerField()),
                ('checkIn', models.DateTimeField()),
                ('checkOut', models.DateTimeField(blank=True, null=True)),
                ('enUso', models.BooleanField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('perfil', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
