# Generated by Django 4.2.4 on 2023-11-27 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroalojamiento',
            name='idHabitacion',
        ),
        migrations.RemoveField(
            model_name='registroalojamiento',
            name='idPasajero',
        ),
        migrations.RemoveField(
            model_name='registroalojamiento',
            name='idServicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='idResponsable',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.AddField(
            model_name='registroalojamiento',
            name='habitacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.habitacion'),
        ),
        migrations.AddField(
            model_name='registroalojamiento',
            name='pasajero',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.pasajero'),
        ),
        migrations.AddField(
            model_name='registroalojamiento',
            name='servicio',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='responsable',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default=None, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('cantidad_dias', models.PositiveIntegerField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.habitacion')),
            ],
        ),
    ]
