# Generated by Django 5.0 on 2023-12-21 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_registroalojamiento_idhabitacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='responsable',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.pasajero'),
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='rut',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='reservas',
            field=models.ManyToManyField(blank=True, to='App1.reserva', verbose_name='Reservas'),
        ),
        migrations.CreateModel(
            name='AdministradorHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.encargado')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='encargado',
            name='persona',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.persona'),
        ),
        migrations.AddField(
            model_name='pasajero',
            name='persona',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.persona'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
