# Generated by Django 4.1.4 on 2023-12-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_perfil_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado',
            name='persona',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='enUso',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroalojamiento',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='AdministradorHotel',
        ),
        migrations.DeleteModel(
            name='Encargado',
        ),
    ]
