# Generated by Django 4.1.4 on 2023-12-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_remove_pasajero_reservas_remove_pasajero_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='App1.pasajero'),
        ),
    ]
