# Generated by Django 4.1.4 on 2023-12-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_alter_reserva_pasajero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='estado',
            new_name='es_responsable',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='responsable',
        ),
        migrations.AddField(
            model_name='pasajero',
            name='servicios',
            field=models.ManyToManyField(through='App1.RegistroAlojamiento', to='App1.servicio'),
        ),
        migrations.AlterField(
            model_name='registroalojamiento',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='App1.servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='checkIn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='registroalojamiento',
            unique_together={('servicio', 'pasajero')},
        ),
        migrations.RemoveField(
            model_name='registroalojamiento',
            name='es_responsable',
        ),
    ]
