# Generated by Django 4.1.4 on 2023-12-26 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_rename_estado_servicio_es_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='servicios',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='es_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_responsables', to='App1.pasajero'),
        ),
    ]
