# Generated by Django 4.1.4 on 2023-12-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_remove_pasajero_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=15),
        ),
    ]
